function rule(~,~)
clf;
ui.CData=imread('游戏界面.jpg');
ui.CData=imresize(ui.CData,[1000,1000]);
ui.CData(:,:,1)=flipud(ui.CData(:,:,1));
ui.CData(:,:,2)=flipud(ui.CData(:,:,2));
ui.CData(:,:,3)=flipud(ui.CData(:,:,3));
ui.Size=size(ui.CData);
Mainaxes=axes('position',[0 0 1 1],...  % 坐标轴左下角位于(0,0)，宽度和高度均为1
    'XLim',[0 ui.Size(2)],...  % x轴范围
    'YLim',[0 ui.Size(1)],...  % y轴范围
    'XTick',0:100:1000,...  % x轴刻度
    'YTick',0:100:1000,...  % y轴刻度
    'NextPlot','add',...  % 在现有坐标区上添加新绘图。在显示新绘图之前，不删除现有绘图或重置坐标区属性。
    'layer','bottom',...  % 在图形对象下方显示刻度线和网格线。
    'Visible','off',...  % 显示坐标区及其子集
    'XGrid','off',...  % 显示x轴网格
    'YGrid','off');  % 显示y轴网格
Drawgui=image([0 ui.Size(2)],[0 ui.Size(1)],ui.CData,'AlphaData',0.4);

textrule1=text('string',...
    '回合制战棋游戏，两位玩家对战。',...
    'position',[60,930],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule2=text('string',...
    '游戏开始时每位玩家有五十颗钻石，每回合玩家可选择',...
    'position',[60,860],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule3=text('string',...
    '招募一名步兵、骑兵或弓箭手。招募步兵需消耗20颗钻',...
    'position',[60,810],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule4=text('string',...
    '石，招募骑兵或弓箭手需消耗25颗钻石。',...
    'position',[60,760],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule5=text('string',...
    '不同兵种有不同特点：步兵攻防均衡；骑兵消灭敌军后',...
    'position',[60,690],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule6=text('string',...
    '可继续攻击；弓箭兵只能远程攻击，无法近战。',...
    'position',[60,640],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule7=text('string',...
    '士兵在招募回合无法移动或攻击，此后每回合可移动或',...
    'position',[60,570],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule8=text('string',...
    '攻击一次，移动后可攻击范围内的敌军，但攻击后无法',...
    'position',[60,520],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule9=text('string',...
    '移动。',...
    'position',[60,470],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule10=text('string',...
    '按空格键结束回合。每回合结束时增加五颗钻石，每消',...
    'position',[60,400],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule11=text('string',...
    '灭一名敌军增加十颗钻石，钻石不足时无法招募士兵。',...
    'position',[60,350],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');
textrule12=text('string',...
    '首先攻破敌军城池的玩家一方获得胜利。',...
    'position',[60,280],...
    'FontSize',16,'FontName','隶书','FontWeight','Bold','Color','k');

uicontrol('style','pushbutton',...
    'position',[530 20 60 30],...
    'backgroundcolor',[0.93333,0.87451,0.8],...
    'string','返回',...
    'Fontname','隶书','FontSize',12,'callback',@gui2);
end